import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import store from '../redux/'
import { Provider } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tikkerly App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </Provider>
  )
}
